#!/usr/bin/env python3

from pathlib import Path
import os
import re
import sys
import tempfile


REQUIRED = (
    "CONTROL_SUITE_VERSION",
    "CONTROL_MODULE_VERSION",
    "ASF_VERSION",
    "ASF_COMMIT",
    "ASF_PATCH_SHA256",
    "ASF_UI_COMMIT",
    "PLAYTIMEGOALS_VERSION",
    "PLAYTIMEGOALS_COMMIT",
    "DOTNET_SDK_VERSION",
)

VALIDATORS = {
    "CONTROL_SUITE_VERSION":
        re.compile(r"\d+\.\d+\.\d+"),

    "CONTROL_MODULE_VERSION":
        re.compile(r"\d+\.\d+\.\d+\.\d+"),

    "ASF_VERSION":
        re.compile(r"\d+\.\d+\.\d+\.\d+"),

    "ASF_COMMIT":
        re.compile(r"[0-9a-f]{40}"),

    "ASF_PATCH_SHA256":
        re.compile(r"[0-9a-f]{64}"),

    "ASF_UI_COMMIT":
        re.compile(r"[0-9a-f]{40}"),

    "PLAYTIMEGOALS_VERSION":
        re.compile(r"\d+\.\d+\.\d+\.\d+"),

    "PLAYTIMEGOALS_COMMIT":
        re.compile(r"[0-9a-f]{40}"),

    "DOTNET_SDK_VERSION":
        re.compile(r"\d+\.\d+\.\d+"),
}


def parse_pins(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}

    for lineno, raw in enumerate(
        path.read_text(encoding="utf-8").splitlines(),
        1,
    ):
        line = raw.strip()

        if not line or line.startswith("#"):
            continue

        match = re.fullmatch(
            r"([A-Z][A-Z0-9_]*)=([A-Za-z0-9._-]+)",
            line,
        )

        if not match:
            raise ValueError(
                f"invalid pins syntax at line {lineno}"
            )

        key, value = match.groups()

        if key not in REQUIRED:
            raise ValueError(
                f"unknown pin: {key}"
            )

        if key in values:
            raise ValueError(
                f"duplicate pin: {key}"
            )

        values[key] = value

    missing = [
        key
        for key in REQUIRED
        if key not in values
    ]

    if missing:
        raise ValueError(
            "missing pins: " + ", ".join(missing)
        )

    for key, validator in VALIDATORS.items():
        if not validator.fullmatch(values[key]):
            raise ValueError(
                f"invalid {key}"
            )

    return values


def render(values: dict[str, str]) -> str:
    mapping = (
        (
            "ControlSuiteVersion",
            "CONTROL_SUITE_VERSION",
        ),
        (
            "ControlModuleVersion",
            "CONTROL_MODULE_VERSION",
        ),
        (
            "TargetAsfVersion",
            "ASF_VERSION",
        ),
        (
            "TargetAsfCommit",
            "ASF_COMMIT",
        ),
        (
            "TargetAsfPatchSha256",
            "ASF_PATCH_SHA256",
        ),
        (
            "TargetAsfUiCommit",
            "ASF_UI_COMMIT",
        ),
        (
            "TargetPlaytimeGoalsVersion",
            "PLAYTIMEGOALS_VERSION",
        ),
        (
            "TargetPlaytimeGoalsCommit",
            "PLAYTIMEGOALS_COMMIT",
        ),
        (
            "DotnetSdkVersion",
            "DOTNET_SDK_VERSION",
        ),
    )

    lines = [
        "// <auto-generated />",
        "",
        "namespace ControlCenter;",
        "",
        "internal static class BuildInfo {",
    ]

    for member, key in mapping:
        lines.append(
            f'    internal const string {member} = "{values[key]}";'
        )

    lines.extend(
        [
            "}",
            "",
        ]
    )

    return "\n".join(lines)


def atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    with tempfile.NamedTemporaryFile(
        mode="w",
        encoding="utf-8",
        newline="\n",
        dir=path.parent,
        delete=False,
    ) as handle:
        handle.write(content)
        temporary = Path(handle.name)

    os.replace(
        temporary,
        path,
    )


def main() -> int:
    if len(sys.argv) != 3:
        print(
            "usage: generate-build-info.py "
            "<release/pins.env> <output.cs>",
            file=sys.stderr,
        )
        return 2

    pins_path = Path(sys.argv[1])
    output_path = Path(sys.argv[2])

    try:
        values = parse_pins(pins_path)
        content = render(values)
        atomic_write(output_path, content)
    except (OSError, ValueError) as error:
        print(
            f"BuildInfo generation failed: {error}",
            file=sys.stderr,
        )
        return 1

    print(
        f"Generated BuildInfo: {output_path}"
    )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
